# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Derek Learns 
email: info@derekpiano.com
description: > # this means to ignore newlines until "baseurl:"
  Derek Learns is a blog dedicated to providing how-to's, tips, and tricks using Python. Data vizulaiztion and analysis projects will also be used as Derek is currently working towards fufilling the requirements of becoming a data scientist in the future.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://derekpiano.com" # the base hostname & protocol for your site
twitter_username: TheDerekAdam
github_username:  dereklearns

# Build settings
markdown: kramdown
